SELECT t1.ID, IFNULL(t2.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA t1
LEFT OUTER JOIN (SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID
HAVING PARENT_ID IS NOT NULL) t2 ON t1.ID=t2.ID
ORDER BY t1.ID;