# 차종 세단,SUV인 것 추리기
# 해당 차종 중 대여기록에 1101~1130에 걸리지 않는 것 추리기
# 할인금액 계산 적용
SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE*(100-p.DISCOUNT_RATE)/100*30,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE 
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
      WHERE CAR_TYPE IN ('세단','SUV') 
        AND DURATION_TYPE='30일 이상') p ON c.CAR_TYPE=p.CAR_TYPE
WHERE c.CAR_TYPE IN ('세단','SUV') 
AND 
    NOT EXISTS (
      SELECT 1
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
      WHERE h.CAR_ID = c.CAR_ID
        AND h.START_DATE <= '2022-11-30'
        AND h.END_DATE   >= '2022-11-01'
    )
AND (c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) >= 500000
AND (c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC;