SELECT t1.FOOD_TYPE, t1.REST_ID, t1.REST_NAME, t1.FAVORITES
FROM REST_INFO t1
JOIN (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
        ) t2 ON t1.FOOD_TYPE=t2.FOOD_TYPE AND t2.MAX_FAVORITES=t1.FAVORITES

GROUP BY FOOD_TYPE, REST_ID, REST_NAME
ORDER BY FOOD_TYPE DESC;