SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE s
JOIN USER_INFO u ON u.USER_ID=s.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR, MONTH, u.GENDER;