With recursive gen 
AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT c.ID, c.PARENT_ID, g.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA c 
    JOIN gen g ON c.PARENT_ID = g.ID
)

SELECT  COUNT(*) AS COUNT, g.GENERATION
FROM gen g
LEFT JOIN ECOLI_DATA d ON d.PARENT_ID = g.ID
WHERE d.ID IS NULL
GROUP BY g.GENERATION
ORDER BY g.GENERATION;