with RECURSIVE t1 as (
    select 0 as HOUR
    UNION ALL
    SELECT HOUR+1 FROM t1 where HOUR < 23 )

SELECT t1.HOUR, IFNULL(t2.COUNT, 0)
FROM t1
LEFT JOIN 
(SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS `COUNT`
FROM ANIMAL_OUTS
GROUP BY HOUR
) t2 ON t2.HOUR = t1.HOUR
ORDER BY t1.HOUR;