SELECT t1.USER_ID, t1.NICKNAME, t2.TOTAL_SALES
FROM USED_GOODS_USER t1
JOIN (SELECT SUM(PRICE) AS TOTAL_SALES, WRITER_ID, STATUS
    FROM USED_GOODS_BOARD
    WHERE STATUS='DONE'
    GROUP BY WRITER_ID, STATUS
    HAVING TOTAL_SALES >= 700000) t2
ON t1.USER_ID = t2.WRITER_ID
ORDER BY t2.TOTAL_SALES;
