-- rare인 아이템의 자식 아이템에 대해 추출
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
JOIN (SELECT ITEM_TREE.ITEM_ID
        FROM ITEM_TREE
        JOIN ITEM_INFO ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
        WHERE ITEM_INFO.RARITY='RARE') j ON i.ITEM_ID = j.ITEM_ID
ORDER BY i.ITEM_ID desc;