SELECT MONTH(t1.START_DATE) AS MONTH, t1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY t1
JOIN (SELECT CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01'
    GROUP BY CAR_ID
     HAVING COUNT(*) >= 5) t2 ON t1.CAR_ID = t2.CAR_ID
WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01'
GROUP BY t1.CAR_ID, MONTH
ORDER BY MONTH, t1.CAR_ID DESC;