SELECT t1.CATEGORY, t1.PRICE, t1.PRODUCT_NAME
FROM FOOD_PRODUCT t1
JOIN 
(SELECT CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY) t2 ON t1.PRICE = t2.PRICE AND t1.CATEGORY = t2.CATEGORY
WHERE t1.CATEGORY = '과자' OR t1.CATEGORY='국' OR t1.CATEGORY='김치' OR t1.CATEGORY='식용유'
ORDER BY t1.PRICE DESC;